import {
  Rocket,
  Brain,
  Globe,
  Smartphone,
  Search,
  TrendingUp,
} from "lucide-react";

export const services = [
  {
    slug: "ai-automation",
    title: "AI Automation",
    desc: "Scale your business with intelligent autonomous workflows and custom AI agents.",
    fullDesc: "We architect custom neural networks and autonomous agents that transform how your business operates. From predictive analytics to automated customer service, our AI solutions are built to scale and evolve.",
    icon: Brain,
    iconBg: "#00D9FF1A",
    iconColor: "#00D9FF",
    features: [
      "Custom GPT & LLM Training",
      "Workflow Automation Agents",
      "Predictive Data Analytics",
      "Neural Network Architecture",
    ],
  },
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    desc: "Data-driven strategies that dominate search results and social media engagement.",
    fullDesc: "Our marketing systems combine psychological triggers with algorithmic precision. We don't just generate traffic; we engineer high-converting digital ecosystems that turn visitors into loyal brand advocates.",
    icon: Rocket,
    iconBg: "#7C3AED1A",
    iconColor: "#7C3AED",
    features: [
      "Algorithmic Media Buying",
      "Conversion Rate Optimization",
      "Social Engineering & Virality",
      "Marketing Automation Stacks",
    ],
  },
  {
    slug: "web-development",
    title: "Web Development",
    desc: "Futuristic, high-performance web applications built with the latest technologies.",
    fullDesc: "We build more than websites; we build high-performance digital engines. Using the latest in Next.js, WebGL, and edge computing, our platforms are lightning fast and visually stunning.",
    icon: Globe,
    iconBg: "#00D9FF1A",
    iconColor: "#00D9FF",
    features: [
      "Next.js & React Architectures",
      "Interactive 3D Web Experiences",
      "Scalable Microservices Backend",
      "Cloud-Native Infrastructure",
    ],
  },
  {
    slug: "mobile-apps",
    title: "Mobile Apps",
    desc: "Immersive iOS and Android experiences designed for maximum user retention.",
    fullDesc: "Mobile-first is no longer enough. We build mobile-only experiences that leverage the latest in hardware acceleration and biometrics to provide seamless, addictive user interfaces.",
    icon: Smartphone,
    iconBg: "#7C3AED1A",
    iconColor: "#7C3AED",
    features: [
      "Native iOS & Android Development",
      "Cross-Platform Flutter Solutions",
      "Real-time Data Sync",
      "Biometric Security Integration",
    ],
  },
  {
    slug: "seo-optimization",
    title: "SEO Optimization",
    desc: "AI-powered search engine optimization to keep you at the top of every query.",
    fullDesc: "Search is evolving, and so should your strategy. We use AI to analyze search intent and semantic relationships, ensuring your brand stays ahead of algorithm shifts and generative search results.",
    icon: Search,
    iconBg: "#00D9FF1A",
    iconColor: "#00D9FF",
    features: [
      "AI-Powered Keyword Intelligence",
      "Semantic Content Engineering",
      "Technical Authority Building",
      "Generative Search Optimization",
    ],
  },
  {
    slug: "trading-tech",
    title: "Trading Tech",
    desc: "Advanced algorithmic trading systems for PSX, PMEX, and Crypto markets.",
    fullDesc: "We bring institutional-grade trading technology to ambitious investors. Our systems utilize low-latency architectures and machine learning to identify and execute alpha-generating opportunities.",
    icon: TrendingUp,
    iconBg: "#7C3AED1A",
    iconColor: "#7C3AED",
    features: [
      "Algorithmic Execution Engines",
      "Market Making Algorithms",
      "Real-time Portfolio Risk AI",
      "Low-Latency API Integration",
    ],
  },
];
